### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by cooldudemaster** [Lahrenheit/EDOPRO-Soundpack#1]
Fails to download from the repos.
![imagen](https://github.com/user-attachments/assets/ac0b737f-8367-40f9-adc7-66f62e0cfd16)

OS is Artix Linux, EDOPro downloaded directly from official page.

**Comment by Lahrenheit** [comment]
Hi, I've tested using my phone (android edopro) and in windows with no issues; in linux i dont test but is strange that it dont work because it uses almost the same json code that skinpack 

![Screenshot_20241021_141412](https://github.com/user-attachments/assets/af179d04-4394-4ab4-9a19-eac96cac099b)

You can download as .zip and uncompress into sound folder

![Screenshot_20241021_141550_Chrome~2](https://github.com/user-attachments/assets/152eb3bb-4388-4974-a7b4-ba3e9465802a)
